from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1054)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 130, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(12, 12, 1441, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1490, 12, 391, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(34)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 230, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 330, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 330, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 430, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 530, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 630, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 730, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 830, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(1350, 140, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setEnabled(True)
        self.checkBox_2.setGeometry(QtCore.QRect(1350, 240, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setGeometry(QtCore.QRect(1350, 340, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setEnabled(True)
        self.checkBox_4.setGeometry(QtCore.QRect(1350, 440, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_55 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_55.setEnabled(True)
        self.checkBox_55.setGeometry(QtCore.QRect(1350, 840, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox_55.setFont(font)
        self.checkBox_55.setObjectName("checkBox_55")
        self.checkBox_65 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_65.setEnabled(True)
        self.checkBox_65.setGeometry(QtCore.QRect(1350, 740, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox_65.setFont(font)
        self.checkBox_65.setObjectName("checkBox_65")
        self.checkBox_7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_7.setEnabled(True)
        self.checkBox_7.setGeometry(QtCore.QRect(1350, 540, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_8.setEnabled(True)
        self.checkBox_8.setGeometry(QtCore.QRect(1350, 640, 220, 60))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(25)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 1300, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(30)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(0, -20, 1921, 1051))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("nice_forest.jpeg"))
        self.label_11.setObjectName("label_11")
        self.label_11.raise_()
        self.label.raise_()
        self.textEdit.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_55.raise_()
        self.checkBox_65.raise_()
        self.checkBox_7.raise_()
        self.checkBox_8.raise_()
        self.label_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 22))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        self.menuOptions = QtWidgets.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionTodo_list_text_file = QtWidgets.QAction(MainWindow)
        self.actionTodo_list_text_file.setObjectName("actionTodo_list_text_file")
        self.actionNew_todolist = QtWidgets.QAction(MainWindow)
        self.actionNew_todolist.setObjectName("actionNew_todolist")
        self.menuOpen.addAction(self.actionTodo_list_text_file)
        self.menuOptions.addAction(self.actionNew_todolist)
        self.menubar.addAction(self.menuOpen.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Add to the list"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox.setText(_translate("MainWindow", " Done !"))
        self.checkBox_2.setText(_translate("MainWindow", " Done !"))
        self.checkBox_3.setText(_translate("MainWindow", " Done !"))
        self.checkBox_4.setText(_translate("MainWindow", " Done !"))
        self.checkBox_55.setText(_translate("MainWindow", " Done !"))
        self.checkBox_65.setText(_translate("MainWindow", " Done !"))
        self.checkBox_7.setText(_translate("MainWindow", " Done !"))
        self.checkBox_8.setText(_translate("MainWindow", " Done !"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.actionTodo_list_text_file.setText(_translate("MainWindow", "Todo list (text file)"))
        self.actionNew_todolist.setText(_translate("MainWindow", "New todolist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
